name: Runner Validation

on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: self-hosted

    steps:
      - name: System check
        run: |
          hostname
          whoami
          git --version
          docker --version
          docker ps

      - name: Docker test
        run: |
          docker run --rm hello-world
